[pytest]
# Automatic test discovery
python_files = pytest_*.py test_*.py

# Registering markers to avoid PytestUnknownMarkWarning
markers =
    generic: marks tests as generic
    qemu: marks tests for qemu
    host_test: marks tests as host-based
    macos: marks tests for macos

# Default CLI options for Hardware-in-the-Loop (HIL)
# Using serial service to communicate with physical UART
addopts = -v --embedded-services serial --port /dev/ttyS0 --baud 115200